/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DialogueIndexRouteImport } from './routes/dialogue.index'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueIndexRoute = DialogueIndexRouteImport.update({
  id: '/dialogue/',
  path: '/dialogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/dialogue/': typeof DialogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/dialogue': typeof DialogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/dialogue/': typeof DialogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/history' | '/library' | '/login' | '/practice/$slug' | '/dialogue/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/library' | '/login' | '/practice/$slug' | '/dialogue'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/library'
    | '/login'
    | '/practice/$slug'
    | '/dialogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  DialogueIndexRoute: typeof DialogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue/': {
      id: '/dialogue/'
      path: '/dialogue'
      fullPath: '/dialogue/'
      preLoaderRoute: typeof DialogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  DialogueIndexRoute: DialogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
